### ISSUE TITLE
Migration: Duplicate Entry in ticket_flag

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#830]
Is this fixed in 10.1? I just got this error
[Mon Mar  1 16:58:12 2021][Error][Kernel::System::MigrateFromOTRS::CloneDB::Driver::Base::DataTransfer][792] Duplicate entry '328-Seen-25' for key 'ticket_flag_per_user', SQL: 'INSERT INTO ticket_flag (ticket_id, ticket_key, ticket_value, create_time, create_by) VALUES (?, ?, ?, ?, ?)'
Migrating from OTRS 6

_Originally posted by @rkarlsba in https://github.com/RotherOSS/otobo/issues/213#issuecomment-788113139_

**Comment by bschmalhofer** [comment]
Hi Roy, @rkarlsba,
this issue #213 is resolved, as that was about Perl code not compiling.
Your problem is another issue. My first guess is that the data is already inconsistent in the OTRS 6 database. For checking that idea, could you run the following SQL statement on the source database:

```
SELECT DISTINCT ticket_id, ticket_key, create_by, COUNT(*) 
FROM ticket_flag 
GROUP BY ticket_id, ticket_key, create_by 
HAVING COUNT(*) > 1
```

**Comment by rkarlsba** [comment]
> Hi Roy, @rkarlsba,
> this issue #213 is resolved, as that was about Perl code not compiling.
> Your problem is another issue. My first guess is that the data is already inconsistent in the OTRS 6 database. For checking that idea, could you run the following SQL statement on the source database:
> 
> ```
> SELECT DISTINCT ticket_id, ticket_key, create_by, COUNT(*) 
> FROM ticket_flag 
> GROUP BY ticket_id, ticket_key, create_by 
> HAVING COUNT(*) > 1
> ```

Thanks. I found 83 rows with duplicates here. Any idea how to remove them?

**Comment by bschmalhofer** [comment]
@rkarlsba,
sorry, I'm not really familiar with what the table _ticket_flag_ is used for.  A quick search showed that the OTRS Console Command `Maint::Ticket::InvalidUserCleanup` might clean up unneeded entries. Otherwise you would need to check whether that data is useful for you and clean it up maybe manually.

Hope that helps, closing this issue.

**Comment by rkarlsba** [comment]
Apparently, that didn't work. The job is run but the query above still shows duplicates, the exact number as earlier.

**Comment by svenoe** [comment]
Hi Roy,

I don't think there is a command or so to fix your old DB, I'm afraid. Basically this state should never occur in the first place, and their is no way to automatically decide which Tickets you want to keep, and which are unimportant. (You could probably also give them other IDs, but then all other objects (articles, customers,...) which reference them won't do that anymore.) So in the end this is something you will have to resolve by hand I assume.

Sven
